### ISSUE TITLE
RPM packaging issues

### ISSUE THREAD

**Issue by whamblen** [hautreux/auks#55]
After building the RPMs and installing them, I noticed a couple things.  Sorry, I don't know enough to easily provide patches, or fixes to the SPEC file.  

1. Currently, both the systemd service files and the auks command look for auks.conf at /etc/auks.conf but the documentation and example files have it at /etc/auks/auks.conf.  I think /etc/auks/auks.conf is probably the preferred location so the results of rpmbuild ought to reflect that.  FWIW, I made a symlink from /etc/ which seems to have made everything work.

2. The ACLFile line in auks.conf refers to /etc/auks/auksd.acl but the example file is auks.acl.example (no 'd') and the man page is also for auks.acl (no 'd').  rpmbuild ought to createauks.conf with a modified ACLFile line.  The workaround here is obvious.  :-)

3. The auksd systemd service file (/usr/lib/systemd/system/auksd.service) does "ExecStart=/usr/sbin/auksd -F $AUKSPRIV_OPTIONS" but it probably ought to be "ExecStart=/usr/sbin/auksd -F $AUKSD_OPTIONS".  This doesn't really matter as long as you use the same name in /etc/sysconfig/auksd but it is confusing to have the variable named AUKSPRIV when configuring auksd.

I hope this feedback is helpful/useful.

Thanks to the developers for all their work!  We are excited to be making progress towards having slurm/auks working on our cluster.

**Comment by hautreux** [comment]
Thanks for the feedback.

For the point 1/, the provided auks.spec should create the conf directory /etc/auks and make sure that daemons and clis are using /etc/auks/* files at compile time using a SYSCONFDIR define. I am suprised that you get scripts and clis pointing to /etc/auks.conf.

For the point 2/, you are right, I will modify the example to use auks.acl instead of auksd.acl.

For point 3/, you are right too, but modifying this would introduce incompatibility fo users already using auksd with the badly named AUKSPRIV_OPTIONS variable. So I think that I would let it this way...

**Comment by hautreux** [comment]
point 2/ fixed in 16cd3b0170d677183528f3dc9651d44c9c76fcf4
